### ISSUE TITLE
Missing `babel-preset-react` dependency

### ISSUE THREAD

**Issue by AlesRuzickaEu** [marcusasplund/hyperapp-todo-parcel#8]
Installation does not work unless you have `babel-preset-react`, you have to add `babel-preset-react` (or have it in global storage?).

**Comment by marcusasplund** [comment]
Sorry for late reply. I believe this could occur when you have an older parcel version globally installed.
What do you get when running ```parcel --version``` ?

**Comment by AlesRuzickaEu** [comment]
Sorry, I do not have project here anymore, so I can't check.
I did not have parcel installed globally, so this should not be the reason.

It felt like you have `babel-preset-react` installed (globally, or just not save in `package.json`) and project does not work right away. It was simple fix.

Thank you.
